# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'User_report.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_User_report(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(750, 800)
        Form.setStyleSheet(
            """
            #Form {
                background-image: url('./images/ackground.jpg');
                background-position: center;
                background-repeat: no-repeat;
            }
            """
        )
        self.title = QtWidgets.QLabel(Form)
        self.title.setGeometry(QtCore.QRect(240, 50, 300, 90))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.user_output = QtWidgets.QListView(Form)
        self.user_output.setGeometry(QtCore.QRect(170, 190, 400, 500))
        self.user_output.setObjectName("user_output")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title.setText(_translate("Form", "Moviepoint"))
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    User_report = QtWidgets.QWidget()
    ui = Ui_User_report()
    ui.setupUi(User_report)
    User_report.show()
    sys.exit(app.exec_())

